-- SuperSurvivorsOrders.lua
-- Global Survivor Orders for use in menus and logic

Orders = {
    "Barricade",
    "Chop Wood",
    "Clean Up Inventory",
    "Doctor",
    "Explore",
    "Follow",
    "Farming",
    "Forage",
    "Gather Wood",
    "Go Find Food",
    "Go Find Water",
    "Go Find Weapon",
    "Guard",
    "Lock Doors",
    "Loot Room",
    "Patrol",
    "Sort Loot Into Base",
    "Stand Ground",
    "Stop",
    "Dismiss",
    "Relax",
    "Return To Base",
    "Pile Corpses",
    -- New Orders:
    "Loot Canned Food",
    "Find Can Opener",
    "Scout Building"
}

OrderDesc = {
    ["Barricade"] = getText("ContextMenu_SS_OrderDesc_Barricade"),
    ["Chop Wood"] = getText("ContextMenu_SS_OrderDesc_Chop_Wood"),
    ["Clean Up Inventory"] = getText("ContextMenu_SS_OrderDesc_Clean_Up_Inventory"),
    ["Doctor"] = getText("ContextMenu_SS_OrderDesc_Doctor"),
    ["Explore"] = getText("ContextMenu_SS_OrderDesc_Explore"),
    ["Follow"] = getText("ContextMenu_SS_OrderDesc_Follow"),
    ["Farming"] = getText("ContextMenu_SS_OrderDesc_Farming"),
    ["Forage"] = getText("ContextMenu_SS_OrderDesc_Forage"),
    ["Gather Wood"] = getText("ContextMenu_SS_OrderDesc_Gather_Wood"),
    ["Go Find Food"] = getText("ContextMenu_SS_OrderDesc_Go_Find_Food"),
    ["Go Find Water"] = getText("ContextMenu_SS_OrderDesc_Go_Find_Water"),
    ["Go Find Weapon"] = getText("ContextMenu_SS_OrderDesc_Go_Find_Weapon"),
    ["Guard"] = getText("ContextMenu_SS_OrderDesc_Guard"),
    ["Lock Doors"] = getText("ContextMenu_SS_OrderDesc_Lock_Doors"),
    ["Loot Room"] = getText("ContextMenu_SS_OrderDesc_Loot_Room"),
    ["Patrol"] = getText("ContextMenu_SS_OrderDesc_Patrol"),
    ["Sort Loot Into Base"] = getText("ContextMenu_SS_OrderDesc_Sort_Loot"),
    ["Stand Ground"] = getText("ContextMenu_SS_OrderDesc_Stand_Ground"),
    ["Stop"] = getText("ContextMenu_SS_OrderDesc_Stop"),
    ["Dismiss"] = getText("ContextMenu_SS_OrderDesc_Dismiss"),
    ["Relax"] = getText("ContextMenu_SS_OrderDesc_Relax"),
    ["Return To Base"] = getText("ContextMenu_SS_OrderDesc_Return_To_Base"),
    ["Pile Corpses"] = getText("ContextMenu_SS_OrderDesc_Pile_Corpses"),
    -- New Order Descriptions
    ["Loot Canned Food"] = getText("ContextMenu_SS_OrderDesc_Loot_Canned_Food"),
    ["Find Can Opener"] = getText("ContextMenu_SS_OrderDesc_Find_Can_Opener"),
    ["Scout Building"] = getText("ContextMenu_SS_OrderDesc_Scout_Building")
}

OrderDisplayName = {
    ["Barricade"] = getText("ContextMenu_SS_OrderDisplayName_Barricade"),
    ["Chop Wood"] = getText("ContextMenu_SS_OrderDisplayName_Chop_Wood"),
    ["Clean Up Inventory"] = getText("ContextMenu_SS_OrderDisplayName_Clean_Up_Inventory"),
    ["Doctor"] = getText("ContextMenu_SS_OrderDisplayName_Doctor"),
    ["Explore"] = getText("ContextMenu_SS_OrderDisplayName_Explore"),
    ["Follow"] = getText("ContextMenu_SS_OrderDisplayName_Follow"),
    ["Farming"] = getText("ContextMenu_SS_OrderDisplayName_Farming"),
    ["Forage"] = getText("ContextMenu_SS_OrderDisplayName_Forage"),
    ["Gather Wood"] = getText("ContextMenu_SS_OrderDisplayName_Gather_Wood"),
    ["Go Find Food"] = getText("ContextMenu_SS_OrderDisplayName_Go_Find_Food"),
    ["Go Find Water"] = getText("ContextMenu_SS_OrderDisplayName_Go_Find_Water"),
    ["Go Find Weapon"] = getText("ContextMenu_SS_OrderDisplayName_Go_Find_Weapon"),
    ["Guard"] = getText("ContextMenu_SS_OrderDisplayName_Guard"),
    ["Lock Doors"] = getText("ContextMenu_SS_OrderDisplayName_Lock_Doors"),
    ["Loot Room"] = getText("ContextMenu_SS_OrderDisplayName_Loot_Room"),
    ["Patrol"] = getText("ContextMenu_SS_OrderDisplayName_Patrol"),
    ["Sort Loot Into Base"] = getText("ContextMenu_SS_OrderDisplayName_Sort_Loot"),
    ["Stand Ground"] = getText("ContextMenu_SS_OrderDisplayName_Stand_Ground"),
    ["Stop"] = getText("ContextMenu_SS_OrderDisplayName_Stop"),
    ["Dismiss"] = getText("ContextMenu_SS_OrderDisplayName_Dismiss"),
    ["Relax"] = getText("ContextMenu_SS_OrderDisplayName_Relax"),
    ["Return To Base"] = getText("ContextMenu_SS_OrderDisplayName_Return_To_Base"),
    ["Pile Corpses"] = getText("ContextMenu_SS_OrderDisplayName_Pile_Corpses"),
    -- New Order Display Names
    ["Loot Canned Food"] = getText("ContextMenu_SS_OrderDisplayName_Loot_Canned_Food"),
    ["Find Can Opener"] = getText("ContextMenu_SS_OrderDisplayName_Find_Can_Opener"),
    ["Scout Building"] = getText("ContextMenu_SS_OrderDisplayName_Scout_Building")
}
